# Generated by Django 5.0.6 on 2024-05-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Password',
            field=models.CharField(max_length=100),
        ),
    ]
