# Generated by Django 5.0.6 on 2024-05-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Password',
            field=models.IntegerField(),
        ),
    ]
