# Generated by Django 5.0.6 on 2024-05-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_student_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=300)),
                ('Descriptions', models.CharField(max_length=300)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
