# Generated by Django 5.0.6 on 2024-05-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_student_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='Password',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
