# Generated by Django 5.0.6 on 2024-05-16 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_query_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='Password',
        ),
    ]
